on: [push]
name: Azure ARM
env:
  AZURE_FUNCTIONAPP_NAME: 'durablecomedy'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './DurableComedy'
  DOTNET_VERSION: '6.0.202'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./DurableComedy/deploy.bicep
        failOnStdErr: false
        
      # Set Up .NET Environment
    - name: Setup DotNet 6.x Environment
      uses: actions/setup-dotnet@v1
      with: 
          dotnet-version: '6.0.x'
          include-prerelease: true
          
    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
          
      # Run Azure Function Deployment
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
